name: CI - build and test

on:                                
  push:
    branches: [ main ]

jobs:
  build:                           

    runs-on: ubuntu-latest         

    steps:    
    - uses: actions/checkout@v2
      with:
         fetch-depth: 0
         token: ${{ secrets.GITLAB2_WEBSITE_PAT }}
    - name: Set up JDK 11
      uses: actions/setup-java@v2        
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew              
    - name: Build and test
      run: ./gradlew build
    - name: Generate reports by hand, by the command line
      run: ./gradlew reports
    - name: Make the directory for gh-pages branch
      run: mkdir build/gh-pages
    - name: Go into the build directory
      run: 'cd build/; ls; cp -r ./docs/ ./gh-pages/; cp -r ./reports/ ./gh-pages/; ls ./gh-pages'
    - name: Deploy #Taken from https://github.com/marketplace/actions/add-commit
      uses: EndBug/add-and-commit@v7.5.0
      with:
        branch: gh-pages
        message: 'Updating the website.'